#!/bin/zsh
# Convert Lucide CSS to Sciter-compatible format
# Downloads latest font + CSS, outputs Sciter-ready lucide.css
# Usage: ./scripts/convert-lucide.sh

SCRIPT_DIR="${0:A:h}"
PROJECT_DIR="$SCRIPT_DIR/.."
OUTPUT="$PROJECT_DIR/styles/lucide.css"
FONT_DIR="$PROJECT_DIR/fonts"
UNPKG="https://unpkg.com/lucide-static@latest/font"

mkdir -p "$FONT_DIR"

# Always fetch latest
echo "Downloading lucide font + css..."
curl -sL "$UNPKG/lucide.ttf" -o "$FONT_DIR/lucide.ttf"
TMP=$(mktemp)
curl -sL "$UNPKG/lucide.css" -o "$TMP"

echo "Converting for Sciter..."

cat > "$OUTPUT" << 'EOF'
/**
 * Lucide Icons for Sciter
 * Full icon library - https://lucide.dev
 * Auto-generated by scripts/convert-lucide.sh
 */

@font-face {
  font-family: "lucide";
  src: url(../fonts/lucide.ttf);
}

[class^="icon-"] {
  font-family: "lucide";
  font-style: normal;
  font-weight: 400;
  font-size: 16dip;
  line-height: 20dip;
  display: inline-block;
  width: 20dip;
  height: 20dip;
  vertical-align: middle;
  overflow: visible;
}

EOF

grep '^\.icon-' "$TMP" >> "$OUTPUT"
ICONS=$(grep -c '^\.icon-' "$OUTPUT")
rm -f "$TMP"

echo "Done: $ICONS icons in styles/lucide.css"
